---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Set ansible_distribution to Ubuntu if running Pop!_OS
      set_fact: ansible_distribution="Ubuntu"
      when: ansible_distribution == "Pop!_OS"
  roles:
    - general
    - geerlingguy.pip
    - geerlingguy.docker
    - gantsign.visual-studio-code
    - brave-browser
    - tailscale
    - gitkraken
    - nextcloud_client
    - teleport
    - spotify
  vars:
    default_user: kapper
    pip_install_packages:
      - name: docker
    docker_install_compose: true
    docker_users:
      - "{{ default_user }}"
    apt_pkgs:
      - htop
      - tmux
      - zsh
      - apt-transport-https
      - curl
      - slack-desktop
