---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Set ansible_distribution to Ubuntu if running Pop!_OS
      set_fact: ansible_distribution="Ubuntu"
      when: ansible_distribution == "Pop!_OS"
  vars:
    default_user: kapper
  vars_files:
    - vars/main.yml
  roles:
    - general
    - apt
    - gitkraken
    - nextcloud_client
    - nvidia.nvidia_driver
    #- nvidia.nvidia_docker #not working atm
