---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Set ansible_distribution to Ubuntu if running Pop!_OS
      set_fact: ansible_distribution="Ubuntu"
      when: ansible_distribution == "Pop!_OS"
  vars:
    default_user: kapper
  vars_files:
    - vars/main.yml
  roles:
    - general
    - flatpaks
    - snaps
    - ms-teams
    - docker
    - vscode
    - brave-browser
    - spotify-client
    - tailscale
    - teleport
    - nextcloud_client
    - r
    - nvidia.nvidia_driver
    # not working atm due to distribution being overwritten to popos by the role itself
    #- nvidia.nvidia_docker
  tasks:
    - name: Install APT packages
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        autoremove: yes
      with_items: 
        - "{{ apt_pkgs }}"
