---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Set ansible_distribution to Ubuntu if running Pop!_OS
      set_fact: ansible_distribution="Ubuntu"
      when: ansible_distribution == "Pop!_OS"
    - name: Stop packagekitd temporarily
      service:
        name: packagekit
        state: stopped
      changed_when: false
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
  vars_files:
    - vars/main.yml
  roles:
    - role: general
      tags: general
    - role: yubikey
      tags: yubikey
    # - role: geerlingguy.swap
    #   tags: swap
    - role: flatpaks
      tags: flatpaks
    - role: snaps
      tags: snaps
    - role: docker
      tags: docker
    - role: vscode
      tags: vscode
    - role: 1password
      tags: 1password
    - role: brave-browser
      tags: brave-browser
    - role: spotify-client
      tags: spotify-client
    - role: tailscale
      tags: tailscale
    - role: teleport
      tags: teleport
    - role: nextcloud_client
      tags: nextcloud_client
    - role: r
      tags: r
  tasks:
    - name: Install APT packages
      apt:
        name: "{{ item.name | default(omit) }}"
        deb: "{{ item.deb | default(omit) }}"
        state: "{{ item.state }}"
        autoremove: yes
      with_items:
        - "{{ apt_pkgs }}"
  post_tasks:
    - name: Start packagekitd again
      service:
        name: packagekit
        state: started
      changed_when: false
