---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Set ansible_distribution to Ubuntu if running Pop!_OS
      set_fact: ansible_distribution="Ubuntu"
      when: ansible_distribution == "Pop!_OS"
  vars:
    default_user: kapper
  vars_files:
    - vars/main.yml
  roles:
    - general
    - apt
    - flatpaks
    - nextcloud_client
    - nvidia.nvidia_driver
    # not working atm due to distribution being overwritten to popos by the role itself
    #- nvidia.nvidia_docker
  tasks:
    - name: Install nautilus extension to enable 'open folder in code'
      shell: "wget -qO- https://raw.githubusercontent.com/kasperskytte/code-nautilus/master/install.sh | bash"
      become_user: "{{ default_user }}"