- name: "Temporarily disable packagekit to avoid apt lock in the background"
  service:
    name: packagekit
    state: stopped
  changed_when: false

- name: "Add APT repository (loop)"
  include_tasks: add_repo.yml
  loop: "{{ apt_repos }}"
  loop_control:
    loop_var: repo

- name: Purge APT packages
  become: true
  apt:
    pkg: "{{ apt_pkgs_purge }}"
    state: absent
    purge: yes

- name: Install APT packages
  become: true
  apt:
    pkg: "{{ apt_pkgs_install }}"
    state: latest
    autoremove: yes

- name: Re-enable packagekit
  service:
    name: packagekit
    state: started
  changed_when: false