---
#taken from https://brave.com/linux/
- name: Get keyring file
  become: true
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: "/usr/share/keyrings/brave-browser-archive-keyring.gpg"
    mode: "0644"
  become: true

- name: Add Brave repository to list of repositories
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    echo 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main' |\
      sudo tee -a /etc/apt/sources.list.d/brave-browser-release.list
    creates=/etc/apt/sources.list.d/brave-browser-release.list
  args:
    executable: /bin/bash

- name: Update apt cache
  become: true
  ansible.builtin.apt: update_cache=yes
  become: true

- name: Install Brave
  become: true
  ansible.builtin.apt:
    name: brave-browser
    state: present
  become: true

# set brave the default browser
#some setting under Default Applications in ~/.config/mimeapps.list