---
- name: "Password-less sudo for all users"
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Set local user's default shell and generate SSH key
  become: true
  user:
      name: "{{ default_user }}"
      shell: /usr/bin/zsh
      generate_ssh_key: yes

- name: Remove Firefox
  apt:
    name: firefox
    state: absent
