---
- name: "Password-less sudo for all users"
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Ensure zsh is installed
  apt:
    name: zsh
    state: present
  when: default_user_shell_zsh | bool

- name: "Ensure default user has been added correctly"
  user:
    name: "{{ default_user }}"
    home: "/home/{{ default_user }}"
    move_home: yes
    shell: "{{ '/usr/bin/zsh' if default_user_shell_zsh | bool else '/bin/bash' }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    state: present
