---
- name: Retrieve tailscale APT signing key
  become: true
  apt_key:
    url: "https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.gpg"
    state: present

- name: Add tailscale APT repository
  become: true
  apt_repository:
    repo: 'deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main'
    filename: tailscale
    state: present

- name: Install tailscale
  become: true
  apt:
    name: tailscale
    state: latest
    update_cache: true

