- name: Add APT repository
  include_role:
    name: apt_repo
  loop: 
    - {
        name: "ms-teams",
        signing_key_url: "https://packages.microsoft.com/keys/microsoft.asc",
        repo_source_string: "https://packages.microsoft.com/repos/ms-teams stable main"
      }
  loop_control:
    loop_var: repo

- name: Install teams
  apt:
    name: teams
    state: present
    autoremove: true
