- name: Add Teleport apt signing key
  become: true
  apt_key:
    url: https://deb.releases.teleport.dev/teleport-pubkey.asc
    state: present

- name: Add Teleport APT repository
  become: true
  apt_repository:
    repo: deb https://deb.releases.teleport.dev/ stable main
    state: present
    update_cache: yes

- name: Install teleport
  become: true
  apt:
    name: teleport
    state: present