- name: Install Nextcloud desktop client
  become: true
  apt:
    name: nextcloud-desktop
    state: latest

- name: "Ensure {{ ansible_env.HOME }}/.config/autostart folder exists"
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory
    mode: 0775

- name: Auto start Nextcloud desktop client on login
  copy:
    src: nextcloud_client.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/nextcloud_client.desktop"
    mode: 0755
