- name: Add APT repository
  include_role:
    name: apt_repo
  loop: 
    - {
        name: "1password",
        signing_key_url: "https://downloads.1password.com/linux/keys/1password.asc",
        repo_source_string: "https://downloads.1password.com/linux/debian/amd64 stable main"
      }
  loop_control:
    loop_var: repo

- name: Ensure debsig-verify policy folder exists
  file:
    path: "/etc/debsig/policies/AC2D62742012EA22/"
    state: directory
    owner: "root"
    group: "root"
    mode: 0775
    recurse: true
  register: debsig_policy

- name: Check whether debsig-verify policy already exists
  stat:
    path: "{{ debsig_policy.path }}/1password.pol"
  register: debsig_policy_exists

- name: Get debsig-verify policy
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: "{{ debsig_policy.path }}/1password.pol"
    owner: "root"
    group: "root"
    mode: '0440'
  when: not debsig_policy_exists.stat.exists

- name: Create folder for debsig-verify keyring
  file:
    path: "/usr/share/debsig/keyrings/AC2D62742012EA22"
    state: directory
    owner: "root"
    group: "root"
    mode: 0775
    recurse: true
  register: debsig_keyring

- name: Get debsig-verify keyring
  apt_key:
    url: "https://downloads.1password.com/linux/keys/1password.asc"
    keyring: "{{ debsig_keyring.path }}/debsig.gpg"
    state: present

- name: Install 1password
  apt:
    name:
      - 1password
      - 1password-cli
    state: present
    autoremove: true
